### PR TITLE
Improvements on value handling

### PR DESCRIPTION
**Pull request by Germain-Italic**
This PR introduces fixes and improvements on value handling, both server-side and client-side.

# Field hints

Show hints below fields (Bootstrap-style) based on column comments.

image

image

# Support for DATE and DATETIME columns

Fixes  _SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column_ errors

On the client side, DATE fields now show as `input type="date"` and DATETIME as `input type="datetime-local"`, with datepickers that rely on browser support (no JS).

image

Please note that as of today, `datetime-local` is not cross-browser (https://caniuse.com/?search=datetime-local)

On the server side, Cruddiy now refers to the default values to avoid MySQL errors due to non-HTML-translatable values. [A new `parse_columns` helper](https://github.com/Germain-Italic/cruddiy/blob/7d36c4f187d14db470244bd846278b8e724129cb/core/helpers.php#L31) which is extensible, deals with DECIMAL and DATETIME default values. It only required a minor change [in the create template](https://github.com/Germain-Italic/cruddiy/blob/7d36c4f187d14db470244bd846278b8e724129cb/core/templates.php#L380) and [in the update template](https://github.com/Germain-Italic/cruddiy/blob/7d36c4f187d14db470244bd846278b8e724129cb/core/templates.php#L457).

I plan to add more helpers in the future so I decided to make it a separate file. It sits in the core/ folder but it is [duplicated during setup](https://github.com/Germain-Italic/cruddiy/blob/7d36c4f187d14db470244bd846278b8e724129cb/core/relations.php#L30) to the core/app folders, so that it can be distributed to end-users without core/ dependency.

_**/!\\** Helpers file requires commit 52f4d631cb333257508edf57cd70865df12860e1 on the no-delete-previous branch to prevent automatic file deletion._

As [per HTML5 spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#local_date_and_time_strings), the value of datetime-local inputs is normalized into a standard form using the letter "T" to separate the date and the time, and the time portion of the string is as short as possible. This is done by leaving out the seconds component if its value is :00.

# Support for NULL ENUMs

ENUM columns do support empty values:

```sql
CREATE TABLE `alltypes` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`enum_def_notnull` ENUM('Y','N') NOT NULL DEFAULT 'Y' COMMENT 'ENUM default "y" not null',
	`enum_nodef_null` ENUM('Y','N') NULL DEFAULT NULL COMMENT 'ENUM default null'
	PRIMARY KEY (`id`)
)
```

Therefore, nullable ENUM columns now include an empty HTML `select option` :

image

# Use table default values in create form

Default values are pulled from MySQL table definition and injected into create.php's form.

image

Regarding DATETIME columns, the HTML5 `datetime-local` type is filled on form display using PHP's `date("Y-m-d\TH:i:s")`. An improvement would be to fill it with MySQL's `NOW()` built-in function, but that would require too much rewriting in the queries, and I'm aiming to patch Cruddiy, not to re-write it 👼. 

image

See commit 8b3c721f008567f585e13f992c9411a60f7872fd for more information.

NB: MySQL does not support default values for DATE type.

> The exception is that, for TIMESTAMP and DATETIME columns, you can specify the CURRENT_TIMESTAMP function as the default

https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html

# Misc - empty EOLs

Many trailing spaces have been deleted using the [eponym VSC plugin](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces).

image

### CODE REVIEW

**Comment by Germain-Italic** [comment]
Merging this branch (allow-null-values) with my other PR from no-delete-previous branch created conflicts in generate.php. Here's the merged branches vith solved conflicts: https://github.com/Germain-Italic/cruddiy/blob/ee6b6ca3123c8871b2aaac8172250f7008939759/core/generate.php

**Comment by jan-vandenberg** [comment]
This looks like an amazing PR! I will look at it in more detail later this week (there are a lot of changes) and pull it in if all works fine. 

Thanks again @Germain-Italic for your great additions!

**Comment by jan-vandenberg** [comment]
I just noticed there is a merge conflict? So I can't pull in the code.

**Comment by Germain-Italic** [comment]
I've resolved the conflict locally yesterday and tested it on my projects since then. I just copy/pasted my solved version of generate.php, you should be able to pull!

**Comment by Germain-Italic** [comment]
@jan-vandenberg I recommend that you merge #19 before accepting #24

**Comment by jan-vandenberg** [comment]
Thank you @Germain-Italic! Excellent additions!

**Comment by Asaiel65** [comment]
> Thank you @Germain-Italic! Excellent additions!

Hi, seems that the date functionnalities (including date pickers) were removed from generate.php on merge 27b8b7d.
Where there any conflict problem? other?

Regards,

**Comment by Germain-Italic** [comment]
> Where there any conflict problem? other?

Unsure, there were fixed conflicts but the PR had to be merged in a certain order.
I still have these features in my fork:

image

Therefore I will be able to submit a new PR.
I'm busy on another project ATM but I will work in it ASAP.

For a quick fix, replace generate.php with https://raw.githubusercontent.com/Germain-Italic/cruddiy/ee6b6ca3123c8871b2aaac8172250f7008939759/core/generate.php

**Comment by Asaiel65** [comment]
> > Where there any conflict problem? other?
> 
> Unsure, there were fixed conflicts but the PR had to be merged in a certain order.
> I still have these features in my fork, along with default values and columns comments:
> 
> image
> 
> Therefore I will be able to submit a new PR.
> I'm busy on another project ATM but I will work in it ASAP.
> 
> For a quick fix, replace generate.php with https://raw.githubusercontent.com/Germain-Italic/cruddiy/ee6b6ca3123c8871b2aaac8172250f7008939759/core/generate.php

Hi,

thx for your answer. I’ll check your files, and follow the PR to come :-)

**Comment by jan-vandenberg** [comment]
I am not sure what happened here, I had to revert some changes a while back. Maybe I reverted too much. 
I look forward to the PR.

**Comment by Asaiel65** [comment]
> I am not sure what happened here, I had to revert some changes a while back. Maybe I reverted too much.
> I look forward to the PR.

Ok, np, thx for your answer, and all the work for this project :-)

**Comment by jan-vandenberg** [comment]
I copied and pasted some code over to the latest Cruddiy release to get a nice datepicker etc. 
https://github.com/jan-vandenberg/cruddiy/releases/tag/v2.4
(For some reason when I try to pull in ALL the code (the mentioned generate.php file), it breaks on my side, so I only copied that what seems to work).

**Pull request merged**
